### ISSUE TITLE
Uploading a single file

### ISSUE THREAD

**Issue by lannonbr** [actions/upload-artifact#3]
Say I wish to upload a screenshot made from [puppeteer](https://github.com/GoogleChrome/puppeteer), can it be possible to upload just the image generated rather than a zip file only containing that image.

**Comment by TingluoHuang** [comment]
you can't since we use the artifact name as a folder to hold all uploaded files.

**Comment by os6sense** [comment]
@TingluoHuang I think that counts as a feature request :)

**Comment by TingluoHuang** [comment]
@os6sense agreed, the UI could have some pop-up dialog to allow you download individual file within your artifact.

**Comment by 1138-4EB** [comment]
IMHO, this action should:

- Support providing a list of items, each being either a folder, a file, or a glob pattern.
- NOT package the content automatically.
- The name should be optional, and only used to create 'sections' in the pop-up, not to name the artifacts. For example:

```
  with:
    title: my-artifacts
      - files: [ path/to/artifact.tar.gz ]
      - name: "Packages"
        files: [ path/to/rpms/*.rpm,  path/to/debs/*.rpm ]
      - name: "Docs"
        files: [ "README.md", path/to/docs ]
```

would create:

- my-artifacts:
  - artifact.tar.gz
  - Packages:
    - package_x86_64.rpm
    - package_aarch64.rpm
    - package_x86_64.deb
    - package_aarch64.deb
  - Docs
    - README.md
    - USE_GUIDE.md
    - CHANGELOG.md

Ideally, the GUI would allow to download each file separately OR a tarball of each of the sections ('Packages' and/or 'Docs', in this examples).

**Comment by Stanzilla** [comment]
Yup, would love to be able to upload files instead. my build process already ends with a zip file and currently this action would just zip the zip.

**Comment by 1138-4EB** [comment]
> Yup, would love to be able to upload files instead. my build process already ends with a zip file and currently this action would just zip the zip.

This is worse with any non-zip package/tarball. For zips I extract them, so they are compressed again.  However, for tar.gz, you get double compression.

**Comment by Stanzilla** [comment]
@damccorm any plans for that?

**Comment by mooreatv** [comment]
I would also love to be able to specify an already made zip or other single file instead of getting zip containing a zip

**Comment by AlexApps99** [comment]
Bump

**Comment by Jeff-Tian** [comment]
Bump

**Comment by 1138-4EB** [comment]
This issue and #7 sum up ~100 reactions. @chrispat, @TingluoHuang, @madhurig, might we have an update about the status of this enhancement request?

**Comment by pelotom** [comment]
Also, I had a process which produced a `.zip` file, and when I discovered this idiosyncrasy I removed that step so that it just uploaded the directory... only to discover that the build now took 20 minutes where before it took ~1. So it appears that when you _do_ upload a folder, it does the zipping on the server instead of the client, which is just... why? I'm left feeling the only reasonable way to use this action is to zip your artifact locally yourself, then upload it and live with the fact that you will have to download a zip containing a zip.

**Comment by jperl** [comment]
Ideally you could upload files uncompressed and be able to reference them by url. That way you could include screenshots within markdown of a status check / comment.

**Comment by chrisdembia** [comment]
This would be fantastic. In particular, the current zipping does not preserve symlinks or the executable bit.

**Comment by filips123** [comment]
@eine @damccorm @madhurig Is there any update about this? I really like idea in https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814. Lack of this is also one of the reasons why I can't use GitHub Actios as my primary CI.

**Comment by eine** [comment]
@filips123, unfortunately, not at all. Label "work in progress" was added to #7 18 days ago, but there has been no comment/update that I am aware.

**Comment by konradpabjan** [comment]
@filips123 @eine Posted an update about `v2` in https://github.com/actions/upload-artifact/issues/7#issuecomment-566114993

**Comment by DalderupMaurice** [comment]
Will the v2 also support globs or uploading of all files in a certain folder? 
I'm currently using electron and I need to upload 12 files (exe's, dmgs, snaps, ymls, ...) but I have to adjust the GH action with every release (as the name changes because the version is included in the name) and I have to define an upload action for every file

**Comment by eine** [comment]
@DalderupMaurice, on the one hand, I think that the relevant new is that the action is going to be open sources. Whether globs or uploading all files is supported should not be relevant once we can all contribute. On the other hand, although not *clean*, you can currently update the names programmatically, so that you don't need to change the names manually for each release. See examples about setting the output of a stage and using it afterwards.

**Comment by konradpabjan** [comment]
The `v2` preview is out and ready for feedback! 😀

For more information see: https://github.com/actions/upload-artifact/issues/62

With the `v2-preview` you can now upload artifacts by specifying
- An individual file
- A directory
- A wildcard pattern

Note: We only currently support downloading an artifact from the GitHub UI by zipping all the files together (this is independent of how the artifact gets uploaded). If you upload an individual file, in the UI the artifact will still present itself as a Zip because that is currently only what we support. We have plans in our roadmap to offer a more enhanced artifact UI that will allow you to browse and download individual files of an artifact. No ETA on when that might arrive, but it is something that we really really want to enhance. 

Some more information about zipping and compression: https://github.com/actions/toolkit/blob/master/packages/artifact/docs/additional-information.md#is-my-artifact-compressed

**Comment by imjasonmiller** [comment]
Wonderful @konradpabjan. thank you for the hard work, it is much appreciated!

**Comment by illera88** [comment]
Hi,
@konradpabjan. I've tried the version 2 to upload a single file but it stills zip it, Is that the intended behaviour?

Thanks

**Comment by konradpabjan** [comment]
@illera88 See my comment: https://github.com/actions/upload-artifact/issues/3#issuecomment-598820814

The zip is provided because of a UI limitation and it is independent of how an artifact gets uploaded

**Comment by illera88** [comment]
Thanks!! Looking forward for the update you mentioned

**Comment by konradpabjan** [comment]
`v2` has officially been released! https://github.blog/changelog/2020-04-28-github-actions-v2-artifact-actions/

With it, you can now specify
- An individual file
- A directory
- A wildcard pattern

The `README` has also been updated with examples on how to upload individual files. I consider this issue fixed so i'll be closing this.

A lot of users many still be confused and think that their artifacts are uploaded as a zip (they're not). Files are uploaded individually one by one. We have some work to do on the UI side of GitHub to allow users to browse and download files individually from an artifact. Right now in order for everything to be downloaded at once, a zip gets dynamically created when you click to download the artifact. This zip is a UI limitation and it is independent of how the artifact gets upload.

UI enhancements can be tracked in this issue (we'll report when we have something to share): https://github.com/actions/upload-artifact/issues/14

I'll be pinning this issue for awareness in-case anyone stumbles upon this and is a little confused as to why they get a zip.

**Comment by eine** [comment]
Thanks @konradpabjan!

After recent updates, most of the features requested [above](https://github.com/actions/upload-artifact/issues/3#issuecomment-524442814) are implemented already:

- [x] Support providing a list of items, each being either a *folder* (current behaviour), a *file* (first comment above), or a *glob pattern* (also requested in #11).
  - [ ] **?** Or an *exclude pattern* ([#44 (comment)](https://github.com/actions/upload-artifact/issues/44#issuecomment-571293418)).
- [ ] NOT package the content automatically.
- [x] The name should be optional, and only used to create 'sections' in the pop-up, not to name the artifacts.
- [ ] **?** GUI would allow to download each file separately OR a tarball of each of the sections ('Packages' and/or 'Docs', in these examples), as suggested by @TingluoHuang.
- [x] Related to #5, each of the files or sections should also have a 'remove' button, only visible to maintainers.
- [ ] Ideally, it would be possible to reorganize the content of the 'artifacts folder'. I.e., move items from a section to another.

Supporting a list of paths/patterns as an alternative to https://github.com/actions/upload-artifact#uploading-to-the-same-artifact is already being tracked in #55.

@konradpabjan, can you please clarify the state of the two items marked with `?`?

**Comment by konradpabjan** [comment]
@eine 

Exclude characters and multiple paths should be added after the major bugs introduced with v2 get sorted out (some of the connection errors reported are pretty serious, so I don't want to add any new features yet. stability > new features). Both of those should be completed at the same time though.

In terms of GUI updates and other improvements.... I don't like to give promises or dates 😂I tend to be off pretty significantly so it's best to just wait.

**Comment by TiagoGouvea** [comment]
The issue seems to be resolved, but I'm facing some problems with it. Upload and download a file on project root. Trying to do a  `cat` on file I got `cat: .env: Is a directory`.

I wrote a [public test action](https://github.com/TiagoGouvea/github-actions-test/runs/732127090?check_suite_focus=true): 
```
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Create .env file
        run: |
          echo "my file content" > .env
          cat .env

      - name: Check .env file
        run: |
          cat .env

      - name: Store .env artifcat
        uses: actions/upload-artifact@v2
        with:
          path: .env

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      - name: Get artifact
        uses: actions/download-artifact@v2
        with:
          path: .env
        
      - name: Check .env file
        run: |
          cat .env
```

What I'm missing out?

**Comment by dentarg** [comment]
@TiagoGouvea see the log from "Get Artifact"

https://github.com/TiagoGouvea/github-actions-test/runs/732127090?check_suite_focus=true#step:3:6

> Artifact artifact was downloaded to /home/runner/work/github-actions-test/github-actions-test/.env/artifact

That should explain it, but if the behaviour is the expected or unexpected from this action, I don't know :)

**Comment by TiagoGouvea** [comment]
Thank you @dentarg for you quick answer and your observation. 

In fact, checking now, there are two situations (show above).

My expected behavior, on any case, would be the file get back to the same path. On both cases it downloaded to a folder.

**With `name: envFile`**

* it downloaded the file to `.env/.env`
* [Public action](https://github.com/TiagoGouvea/github-actions-test/runs/732447281?check_suite_focus=true)

**Without `name`**

* it downloaded the file to `.env/artifact/.env`
* [Public action](https://github.com/TiagoGouvea/github-actions-test/runs/732455524?check_suite_focus=true)

**Comment by bradennapier** [comment]
https://github.com/bradennapier/eslint-plus-action/blob/master/src/artifacts.ts

I just got done doing a bunch of effort to get artifacts handling working really nicely using the api directly instead of the toolkits so all the features can be enabled.  Figure y'all might find it useful since a lot of that took forever :-P 

I still need to do a pass at polishing but it all works well.

**Comment by zakiya27** [comment]
When I am uploading my folder it is getting uploaded in zip format . So, can someone tell me why that is happening as I am not uploading it in a zip format but still it is getting uploaded in a zip mode.

**Comment by MCOfficer** [comment]
Artifacts are always downloaded as zip. If you were to upload a zip, iirc anyone downloading it would get a zip containing a zip.

The `download-artifact` actions gets around that btw.

**Comment by Wohlstand** [comment]
Recently I tried to upload the DMG (it's a compressed package by itself), but I got it packed into ZIP 🤔 
Seems this case isn't completed...

**Comment by MCOfficer** [comment]
> A lot of users many still be confused and think that their artifacts are uploaded as a zip (they're not). Files are uploaded individually one by one. We have some work to do on the UI side of GitHub to allow users to browse and download files individually from an artifact. Right now in order for everything to be downloaded at once, a zip gets dynamically created when you click to download the artifact. This zip is a UI limitation and it is independent of how the artifact gets upload.

**Comment by Wohlstand** [comment]
@MCOfficer, Oh, ok, understood, thanks for the explanation!

**Comment by LeftTwixWand** [comment]
Hi. How can I upload a .nupkg artifact to pipeline Assets without .zip archiving?

**Comment by MCOfficer** [comment]
> Hi. How can I upload a .nupkg artifact to pipeline Assets without .zip archiving?

You can't, currently anything that's uploaded is zipped.

**Comment by xingkong0113** [comment]
hello all 
Is there a plan to solve this issue in 2022?

**Comment by dpowers86** [comment]
At the minimum, if the artifact is just a single file, the web interface shouldn't ZIP the file. Pass the raw file with the proper MIME type so if I upload a PDF or JPEG, I can just click it on the Actions tab and view it in my browser without unzipping it.

Unfortunately this seems to be a common theme with GitHub. Issues that I would consider show-stoppers or at least significant quality of life improvement are just rotting or getting closed without any time table except for "its on the back burner". If I could download individual items via the web or get the URLs from the API, we would likely need to pay GH for more storage. Instead I'll likely just use an S3 bucket and pay Amazon to store my stuff. They will let me set retention policies and a storage class so I can control my costs.

**Comment by recolic** [comment]
> At the minimum, if the artifact is just a single file, the web interface shouldn't ZIP the file. Pass the raw file with the proper MIME type so if I upload a PDF or JPEG, I can just click it on the Actions tab and view it in my browser without unzipping it.
> 
> Unfortunately this seems to be a common theme with GitHub. Issues that I would consider show-stoppers or at least significant quality of life improvement are just rotting or getting closed without any time table except for "its on the back burner". If I could download individual items via the web or get the URLs from the API, we would likely need to pay GH for more storage. Instead I'll likely just use an S3 bucket and pay Amazon to store my stuff. They will let me set retention policies and a storage class so I can control my costs.

Actually. This is how Microsoft do things.

**Comment by fatinfarzanaazizan** [comment]
@konradpabjan are there any updates on this? would be nice to have this feature in 2022. thanks

**Comment by and3rson** [comment]
Any progress on this? Being able to download a non-zipped artifact is absolutely vital.

**Comment by JojOatXGME** [comment]
@and3rson I think #14 is the relevant successor for this topic.

**Comment by khans6** [comment]
I would also like this feature of downloading the uploading artifact if its a single file as it is. It is annoying when it zips an already zipped file

**Comment by dhruv-bansal** [comment]
> Upload-artifact not working for steps running in containers #13

Is this supported added?
With single upload actions can I create different artefacts with different path of files or I have to call this action multiple times?

**Comment by excitoon** [comment]
I would like to have this feature.

**Comment by rexlManu** [comment]
I would really really like to have this feature!

**Comment by ADTC** [comment]
If this is a UI problem, then the solution would be for the UI to detect and modify its download action as follows:

- If the artifact contains exactly 1 file, download the file directly.
- If the artifact contains more than 1 file, zip the files up automatically and download the zip.

Who maintains the UI? Is it part of this repository?

**Comment by DineshRaturi-cpi** [comment]
Do we have any solution for this problem?
I want to upload a .png image on github actions and want to send its URL to slack. But since GitHub actions upload its artficats in zip format, I am unable to do that. Kindly help

**Comment by MCOfficer** [comment]
> Do we have any solution for this problem? I want to upload a .png image on github actions and want to send its URL to slack. But since GitHub actions upload its artficats in zip format, I am unable to do that. Kindly help

Upload it somewhere -anywhere- else. Even nightly.link gives you zip files, so artifacts are not the solution here.

**Comment by torokati44** [comment]
+1 for this feature request... :P

**Comment by bosakRFSpin** [comment]
Needed!

**Comment by MCOfficer** [comment]
Just to be clear, I'm not affiliated with github, that was just me telling you what we're stuck with. As of now, your best option to enable direct downloads is to upload it somewhere else. For example, make a separate repo, and have your CI push artifacts onto that repo's release page. Or push it onto netlify, or an R2 bucket (which has no egress fees).
